spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&stringtype=unspecified
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true

server:
  port: 9090

indexing-settings:
  sites:
#    - url: https://dombulgakova.ru
#      name: Дом Булгакова
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://skillbox.ru
#      name: Skillbox
    - url: https://playback.ru
      name: PlayBack.Ru