name: Testing

on: [ push ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello from Testing!"

  deploy:
    runs-on: ubuntu-latest
    needs: [ testing ]

    steps:
      - name: Print Hello
        run: echo "Hello from Deploying!"