name: CI-CD

on: [ push ]

jobs:
#  compile:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Compile with maven
#        run: mvn compile
#
#  testing:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Testing with maven
#        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: [ testing ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true